### ISSUE TITLE
Button to show differences with previous version

### ISSUE THREAD

**Issue by Nif9** [cosmocode/dokuwiki-plugin-structpublish#20]
### Issue Description

Hello, I wanted to report to you an inconsistent behaviour (to my opinion) observed during the edition of a not yet approved nor published page. I edited it multiple times. Then, Approved and Published it.
When a read only granted user opens the page, he can see a banner providing a button to compare differences to previous version. I were expecting to get the differences between the previous _published_ version, but I get the differences only with the previous edition.
Can you indicate if it is expected or a possible anomaly?
Thank you!

**Comment by annda** [comment]
I was at first confused by your description, because you describe publishing a page for the first time. In that case, the banner does not show any links to previous versions, since no previous (published) version exists.

But the problem you report is a real bug. The link to page differences is wrong. It compares the previous **existing** revision, instead of the previous **published** revision.

**Comment by Nif9** [comment]
Thank you very much :)
